image: elixir:1.8

services:
  - name: postgres:10.0
    alias: localhost

variables:
  POSTGRES_DB: cuyhooks_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  MIX_ENV: test
  SECRET_KEY: Jb0gXUV1+JrmUPB8EsVO2jrGrth8M/2NMWpgn6GpMRLcZ8eY1nOEcovenF5g8Xgt

stages:
  - lint
  - test

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test

lint:
  script:
    - mix format --check-formatted

test:
  stage: test
  script:
    - mix test
